name: JailPlugin
version: 1.0-RELEASE
main: com.example.jail.JailPlugin
author: Soryu-haruma(Asl,haruma9012kirby)
api-version: 1.16
api: 1.21.1-R0.1-SNAPSHOT
url: https://github.com/haruma9012kirby/JailPlugin
commands:
  setjail:
    description: Sets a location as a jail.
  jail:
    description: Jail a player.
  setunjail:
    description: Set an unjail location.
  jaillist:
    description: List all jails and jailed players.
  unjail:
    description: Unjail a player.
  jailtp:
    description: Teleport to a jail.
  jailtp-rp:
    description: Teleport to a jail's release point.
  removejail:
    description: Remove a jail.
  jailinfo:
    description: Show information about a specific jail.
permissions:
  jailplugin.command.setjail:
    description: Allows the user to set a jail location.
    default: op
  jailplugin.command.jail:
    description: Allows the user to jail a player.
    default: op
  jailplugin.command.setunjail:
    description: Allows the user to set an unjail location.
    default: op
  jailplugin.command.jaillist:
    description: Allows the user to list all jails and jailed players.
    default: op
  jailplugin.command.unjail:
    description: Allows the user to unjail a player.
    default: op
  jailplugin.command.jailtp:
    description: Allows the user to teleport to a jail.
    default: op
  jailplugin.command.jailtp-rp:
    description: Allows the user to teleport to a jail's release point.
    default: op
  jailplugin.command.removejail:
    description: Allows the user to remove a jail.
    default: op
  jailplugin.command.jailinfo:
    description: Allows the user to show information about a specific jail.
    default: op
